language: node_js
node_js:
   - node
dist: trusty

cache:
    npm: true
    directories:
        - node_modules

before_script:
  - npm install --silent

script:
   - npm test

notifications:
    on_failure: change

on_success: change