dist: trusty

sudo: required

services:
  - docker

language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm test
  - ./integration-test.sh

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: change
    on_failure: change
