FROM node:9.8.0-alpine

MAINTAINER TripleParity

RUN apk update && \
    apk upgrade

RUN apk add --update python make g++ docker
RUN apk add sqlite

#RUN rc-update add docker boot

EXPOSE 8080

WORKDIR /app
ENV NODE_ENV=development
CMD ./scripts/docks-dev-start.sh
