# Deploy the latest version of docks-api from master branch

version: '3.3'

services:

  api:
    image: tripleparity/docks-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - '8080:8080'
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres:latest
    volumes:
      - type: volume
        source: docks_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  docks_data:
