version: '3.2'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./
        target: /app
    ports:
      - "8081:8080"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8082:8080
