FROM node:9.8.0-alpine

MAINTAINER TripleParity

RUN apk update && \
    apk upgrade

# Install docker
RUN apk add docker && \
    apk add py-pip

# Install docker-compose
RUN pip install docker-compose

# Set environmental flags for docker compose
ENV DOCKER_HOST=unix:///var/run/docker.sock

#RUN rc-update add docker boot

EXPOSE 8080

WORKDIR /app
ENV NODE_ENV=development
CMD ./scripts/docks-dev-start.sh
