version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./
        target: /app
    ports:
      - "8080:8080"
