version: '3.2'

services:

  api:
    image: tripleparity/docks-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example