# Deploy the latest version of docks-api from master branch

version: '3.2'

services:

  api:
    image: tripleparity/docks-api:branch-develop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - '8080:8080'
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres
    volumes:
      - type: volume
        source: docks_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example

volumes:
  docks_data:
